services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: userpass
      DB_NAME: tourism_db
      JWT_SECRET: dev-secret-key-change-in-production
      JWT_ACCESS_SECRET: dev-access-secret-change-in-production
      JWT_REFRESH_SECRET: dev-refresh-secret-change-in-production
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /backend/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    command: npm run dev

  db:
    image: mariadb:10.6
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tourism_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  # business-app:
  #   build: ./business-app
  #   container_name: business
  #   environment:
  #     VITE_SUPABASE_URL: https://ieodjlfkxmhbtgppddhw.supabase.co
  #     VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllb2RqbGZreG1oYnRncHBkZGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTQxNTgsImV4cCI6MjA1OTkzMDE1OH0.Pa0FhIKYtaabxssKYav5I5NL_DCH1hDJ8bgJ6Xd6pi4
  #     NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: AIZaSyCvrFJIDAgujket50Rr8CXQ-gR-_6dpLjs
  #   ports:
  #     - "5173:5173"

  # tourism-admin-app:
  #   build: ./tourism-admin-app
  #   container_name: admin
  #   environment:
  #     VITE_SUPABASE_URL: https://ieodjlfkxmhbtgppddhw.supabase.co
  #     VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllb2RqbGZreG1oYnRncHBkZGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTQxNTgsImV4cCI6MjA1OTkzMDE1OH0.Pa0FhIKYtaabxssKYav5I5NL_DCH1hDJ8bgJ6Xd6pi4
  #     NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: AIZaSyCvrFJIDAgujket50Rr8CXQ-gR-_6dpLjs
  #   ports:
  #     - "5174:5174"

  # city-ventures:
  #   build: ./city-ventures
  #   container_name: city-ventures
  #   environment:
  #     VITE_SUPABASE_URL: https://ieodjlfkxmhbtgppddhw.supabase.co
  #     VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllb2RqbGZreG1oYnRncHBkZGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTQxNTgsImV4cCI6MjA1OTkzMDE1OH0.Pa0FhIKYtaabxssKYav5I5NL_DCH1hDJ8bgJ6Xd6pi4
  #     NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: AIZaSyCvrFJIDAgujket50Rr8CXQ-gR-_6dpLjs
  #   ports:
  #     - "19006:19006"

volumes:
  db_data:
